# Generated by Django 5.1.7 on 2025-03-29 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojinha', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='parcelado',
            field=models.BooleanField(default=False),
        ),
    ]
