# Generated by Django 5.1.7 on 2025-03-29 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojinha', '0002_venda_parcelado'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='quantidade_parcelas',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
