# Generated by Django 5.1.7 on 2025-03-29 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojinha', '0003_venda_quantidade_parcelas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcela',
            name='data_baixa',
            field=models.DateField(default=True),
        ),
    ]
