# Generated by Django 5.1.7 on 2025-03-29 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojinha', '0004_alter_parcela_data_baixa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcela',
            name='data_baixa',
            field=models.DateField(blank=True, null=True),
        ),
    ]
