# Generated by Django 5.1.7 on 2025-03-29 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojinha', '0005_alter_parcela_data_baixa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='parcelado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='venda',
            name='quantidade_parcelas',
            field=models.IntegerField(default=1),
        ),
    ]
