# Generated by Django 5.1.7 on 2025-03-29 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojinha', '0006_alter_venda_parcelado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemvenda',
            name='quantidade',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
