# Generated by Django 5.1.7 on 2025-03-29 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojinha', '0007_alter_itemvenda_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='idade_tamanho',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
