# Generated by Django 5.1.7 on 2025-03-29 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojinha', '0008_alter_produto_idade_tamanho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='idade_tamanho',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
